# -*- coding: utf-8 -*-
"""
Choices of ``critica.apps.positions`` application.

"""

# Category positions
# ------------------------------------------------------------------------------
CATEGORY_POSITION_CADRE_HAUT = 1
CATEGORY_POSITION_CADRE_BAS = 2
CATEGORY_POSITION_POSTIT = 3
CATEGORY_POSITION_PUNAISE_LIGNE1_GAUCHE = 4
CATEGORY_POSITION_PUNAISE_LIGNE1_DROITE = 5
CATEGORY_POSITION_PUNAISE_LIGNE2_GAUCHE = 6
CATEGORY_POSITION_PUNAISE_LIGNE2_DROITE = 7
CATEGORY_POSITION_PUNAISE_LIGNE3_GAUCHE = 8
CATEGORY_POSITION_PUNAISE_LIGNE3_DROITE = 9
CATEGORY_POSITION_PUNAISE_LIGNE4_GAUCHE = 10
CATEGORY_POSITION_PUNAISE_LIGNE4_DROITE = 11
CATEGORY_POSITION_SCOTCH = 12

CATEGORY_POSITION_CHOICES = (
    (CATEGORY_POSITION_CADRE_HAUT, 'Cadre haut'),
    (CATEGORY_POSITION_CADRE_BAS, 'Cadre bas'),
    (CATEGORY_POSITION_POSTIT, 'Post-it'),
    (CATEGORY_POSITION_PUNAISE_LIGNE1_GAUCHE, 'Punaise -- ligne 1 -- gauche'),
    (CATEGORY_POSITION_PUNAISE_LIGNE1_DROITE, 'Punaise -- ligne 1 -- droite'),
    (CATEGORY_POSITION_PUNAISE_LIGNE2_GAUCHE, 'Punaise -- ligne 2 -- gauche'),
    (CATEGORY_POSITION_PUNAISE_LIGNE2_DROITE, 'Punaise -- ligne 2 -- droite'),
    (CATEGORY_POSITION_PUNAISE_LIGNE3_GAUCHE, 'Punaise -- ligne 3 -- gauche'),
    (CATEGORY_POSITION_PUNAISE_LIGNE3_DROITE, 'Punaise -- ligne 3 -- droite'),
    (CATEGORY_POSITION_PUNAISE_LIGNE4_GAUCHE, 'Punaise -- ligne 4 -- gauche'),
    (CATEGORY_POSITION_PUNAISE_LIGNE4_DROITE, 'Punaise -- ligne 4 -- droite'),
    (CATEGORY_POSITION_SCOTCH, 'Scotch'),
)

# Note type positions
# ------------------------------------------------------------------------------
NOTE_TYPE_POSITION_POSTIT = 1
NOTE_TYPE_POSITION_PUNAISE_LIGNE1_GAUCHE = 2
NOTE_TYPE_POSITION_PUNAISE_LIGNE1_DROITE = 3
NOTE_TYPE_POSITION_PUNAISE_LIGNE2_GAUCHE = 4
NOTE_TYPE_POSITION_PUNAISE_LIGNE2_DROITE = 5
NOTE_TYPE_POSITION_ACCORDEON_LIGNE1 = 6
NOTE_TYPE_POSITION_ACCORDEON_LIGNE2 = 7
NOTE_TYPE_POSITION_ACCORDEON_LIGNE3 = 8
NOTE_TYPE_POSITION_ACCORDEON_LIGNE4 = 9
NOTE_TYPE_POSITION_ACCORDEON_LIGNE5 = 10

NOTE_TYPE_POSITION_CHOICES = (
    (NOTE_TYPE_POSITION_POSTIT, 'Post-it'),
    (NOTE_TYPE_POSITION_PUNAISE_LIGNE1_GAUCHE, 'Punaise -- ligne 1 -- gauche'),
    (NOTE_TYPE_POSITION_PUNAISE_LIGNE1_DROITE, 'Punaise -- ligne 1 -- droite'),
    (NOTE_TYPE_POSITION_PUNAISE_LIGNE2_GAUCHE, 'Punaise -- ligne 2 -- gauche'),
    (NOTE_TYPE_POSITION_PUNAISE_LIGNE2_DROITE, 'Punaise -- ligne 2 -- droite'),
    (NOTE_TYPE_POSITION_ACCORDEON_LIGNE1, 'Accordéon -- ligne 1'),
    (NOTE_TYPE_POSITION_ACCORDEON_LIGNE2, 'Accordéon -- ligne 2'),
    (NOTE_TYPE_POSITION_ACCORDEON_LIGNE3, 'Accordéon -- ligne 3'),
    (NOTE_TYPE_POSITION_ACCORDEON_LIGNE4, 'Accordéon -- ligne 4'),
    (NOTE_TYPE_POSITION_ACCORDEON_LIGNE5, 'Accordéon -- ligne 5'),
)


