# -*- coding: utf-8 -*-
"""
Settings of ``critica.apps.positions``.

"""
from critica.apps.positions import choices


# Default category positions
# ------------------------------------------------------------------------------
CATEGORY_DEFAULT_POSITION_NATIONAL = 1
CATEGORY_DEFAULT_POSITION_ETRANGER = choices.CATEGORY_POSITION_CADRE_BAS
CATEGORY_DEFAULT_POSITION_BOUQUINS = choices.CATEGORY_POSITION_POSTIT
CATEGORY_DEFAULT_POSITION_SOCIETE = choices.CATEGORY_POSITION_PUNAISE_LIGNE1_GAUCHE
CATEGORY_DEFAULT_POSITION_NANAS = choices.CATEGORY_POSITION_PUNAISE_LIGNE1_DROITE
CATEGORY_DEFAULT_POSITION_SPORTS = choices.CATEGORY_POSITION_PUNAISE_LIGNE2_GAUCHE
CATEGORY_DEFAULT_POSITION_TELE = choices.CATEGORY_POSITION_PUNAISE_LIGNE2_DROITE
CATEGORY_DEFAULT_POSITION_PIPOLE = choices.CATEGORY_POSITION_PUNAISE_LIGNE3_GAUCHE
CATEGORY_DEFAULT_POSITION_INSOLITE = choices.CATEGORY_POSITION_PUNAISE_LIGNE3_DROITE
CATEGORY_DEFAULT_POSITION_REGIONS = choices.CATEGORY_POSITION_PUNAISE_LIGNE4_GAUCHE
CATEGORY_DEFAULT_POSITION_COUP_DE_GUEULE = choices.CATEGORY_POSITION_SCOTCH

# Default note type positions
# ------------------------------------------------------------------------------
NOTE_TYPE_DEFAULT_POSITION_VOUS_SAVIEZ = choices.NOTE_TYPE_POSITION_POSTIT
NOTE_TYPE_DEFAULT_POSITION_PREMIERE_NOUVELLE = choices.NOTE_TYPE_POSITION_PUNAISE_LIGNE1_GAUCHE
NOTE_TYPE_DEFAULT_POSITION_ON_SEN_SERAIT_PASSE = choices.NOTE_TYPE_POSITION_PUNAISE_LIGNE1_DROITE
NOTE_TYPE_DEFAULT_POSITION_ON_EN_RIRAIT_PRESQUE = choices.NOTE_TYPE_POSITION_PUNAISE_LIGNE2_GAUCHE
NOTE_TYPE_DEFAULT_POSITION_ILS_ONT_OSE = choices.NOTE_TYPE_POSITION_PUNAISE_LIGNE2_DROITE
NOTE_TYPE_DEFAULT_POSITION_LINFO_OFF = choices.NOTE_TYPE_POSITION_ACCORDEON_LIGNE1
NOTE_TYPE_DEFAULT_POSITION_FALLAIT_SEN_DOUTER = choices.NOTE_TYPE_POSITION_ACCORDEON_LIGNE2
NOTE_TYPE_DEFAULT_POSITION_CRITICONS = choices.NOTE_TYPE_POSITION_ACCORDEON_LIGNE3
NOTE_TYPE_DEFAULT_POSITION_CA_CEST_FAIT = choices.NOTE_TYPE_POSITION_ACCORDEON_LIGNE4
NOTE_TYPE_DEFAULT_POSITION_AUCUN_INTERET = choices.NOTE_TYPE_POSITION_ACCORDEON_LIGNE5
