# -*- coding: utf-8 -*-
from critica.apps.categories import choices

# Category image upload path
IMAGE_UPLOAD_PATH = 'upload/categories/'

# Default positions
DEFAULT_POSITION_NATIONAL = choices.POSITION_CADRE_HAUT
DEFAULT_POSITION_ETRANGER = choices.POSITION_CADRE_BAS
DEFAULT_POSITION_BOUQUINS = choices.POSITION_POSTIT
DEFAULT_POSITION_SOCIETE = choices.POSITION_PUNAISE_LIGNE1_GAUCHE
DEFAULT_POSITION_NANAS = choices.POSITION_PUNAISE_LIGNE1_DROITE
DEFAULT_POSITION_SPORTS = choices.POSITION_PUNAISE_LIGNE2_GAUCHE
DEFAULT_POSITION_TELE = choices.POSITION_PUNAISE_LIGNE2_DROITE
DEFAULT_POSITION_PIPOLE = choices.POSITION_PUNAISE_LIGNE3_GAUCHE
DEFAULT_POSITION_INSOLITE = choices.POSITION_PUNAISE_LIGNE3_DROITE
DEFAULT_POSITION_REGIONS = choices.POSITION_PUNAISE_LIGNE4_GAUCHE
DEFAULT_POSITION_COUP_DE_GUEULE = choices.POSITION_SCOTCH

